FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y deluged \
                       transmission-daemon \
                       qbittorrent-nox \
                       rtorrent \
                       python3 \
                       python3-pip \
                       && \
    rm -rf /var/lib/apt/lists/*

RUN sed -i 's/def findCaller(self, stack_info=False):/def findCaller(self, *args, **kwargs):/g' /usr/lib/python3/dist-packages/deluge/log.py

RUN pip3 install -U setuptools pip wheel
ADD test-requirements.txt /
RUN pip3 install -r /test-requirements.txt
