# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerimage:
          - johndoee/test-libtc:20.04
          - johndoee/test-libtc:22.04
          - johndoee/test-libtc:22.04-deluge-2.1.1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Pull docker image
        run: docker pull ${{ matrix.dockerimage }}

      - name: Run tests in image
        run: docker run --rm -v ${GITHUB_WORKSPACE}/libtc:/libtc ${{ matrix.dockerimage }} pytest -p no:cacheprovider "/libtc/"

